using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hypercube.Utilities.Analyzers.Generators;

[Generator]
public sealed class FixedArrayGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Hypercube.Utilities.Attributes.FixedArrayAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributeSymbolProvider = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(AttributeFullName));

        var structSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is StructDeclarationSyntax syntax &&
                    syntax.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)) &&
                    syntax.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var structSyntax = (StructDeclarationSyntax) ctx.Node;
                    return ctx.SemanticModel.GetDeclaredSymbol(structSyntax) as INamedTypeSymbol;
                })
            .Where(s => s is not null);

        var pipeline = structSymbols.Combine(attributeSymbolProvider);

        context.RegisterSourceOutput(pipeline, static (spc, source) =>
        {
            var (symbol, attributeSymbol) = source;
            if (symbol is null || attributeSymbol is null)
                return;

            var attrData = symbol.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeSymbol));

            if (attrData is null)
                return;

            if (attrData.ConstructorArguments.Length == 0 || attrData.ConstructorArguments[0].Value is not int length || length < 0)
                return;

            var ns = symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString();
            var structName = symbol.Name;

            var sourceText = GenerateSource(ns, structName, length);
            
            var hintName = $"{symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}_FixedArray.g.cs"
                .Replace("global::", "")
                .Replace('<', '_')
                .Replace('>', '_');

            spc.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        });
    }

    private static string GenerateSource(string? ns, string structName, int length)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.Append("    ");
        }

        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public partial struct {structName}<T> where T : unmanaged");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {structName}<T> Empty => new {structName}<T>();");
        sb.AppendLine();
        sb.AppendLine($"    public const int Length = {length};");
        sb.AppendLine();
        
        for (var i = 0; i < length; i++)
            sb.AppendLine($"    private T _element{i};");
        
        sb.AppendLine();
        
        sb.AppendLine("    public ref T this[int index]");
        sb.AppendLine("    {");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        get => ref AsSpan()[index];");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        sb.Append(GenerateConstructors(structName, length));

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine(length > 0
            ? "    public Span<T> AsSpan() => MemoryMarshal.CreateSpan(ref _element0, Length);"
            : "    public Span<T> AsSpan() => Span<T>.Empty;");

        sb.AppendLine("}");

        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateConstructors(string structName, int length)
    {
        var sb = new StringBuilder();

        for (var count = 1; count <= length; count++)
        {
            var ctorParams = new StringBuilder();
            for (var i = 0; i < count; i++)
            {
                if (i > 0) ctorParams.Append(", ");
                ctorParams.Append($"T element{i}");
            }

            sb.AppendLine($"    public {structName}({ctorParams})");
            sb.AppendLine("    {");
            for (var i = 0; i < length; i++)
            {
                sb.AppendLine(i < count
                    ? $"        _element{i} = element{i};"
                    : $"        _element{i} = default;");
            }
            
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}