using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hypercube.Utilities.Analyzers.Generators;

[Generator]
public sealed class IdStructGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Hypercube.Utilities.Attributes.IdStructAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structs = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: AttributeFullName,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax,
            transform: static (ctx, _) => (
                Symbol: (INamedTypeSymbol)ctx.TargetSymbol,
                Attribute: ctx.Attributes[0]));

        context.RegisterSourceOutput(
            structs,
            static (spc, source) => Execute(spc, source.Symbol, source.Attribute));
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol symbol, AttributeData attribute)
    {
        var underlyingType = attribute.ConstructorArguments[0].Value as INamedTypeSymbol;
        var nullCast = attribute.ConstructorArguments.Length > 1 && attribute.ConstructorArguments[1].Value is true;

        var typeName = underlyingType?.ToDisplayString() ?? "int";
        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var structName = symbol.Name;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(namespaceName);
        sb.AppendLine("{");

        // Struct Definition
        sb.Append("    [DebuggerDisplay(\"{Value}\")]").AppendLine();
        sb.Append("    [StructLayout(LayoutKind.Sequential)]").AppendLine();
        sb.Append("    public readonly partial struct ").Append(structName).Append(" : IEquatable<").Append(structName).AppendLine(">");
        sb.AppendLine("    {");

        // Field & Constructor
        sb.Append("        public readonly ").Append(typeName).AppendLine(" Value;");
        sb.AppendLine();
        sb.Append("        public ").Append(structName).Append("(").Append(typeName).AppendLine(" value) => Value = value;");
        sb.AppendLine();

        // ToString
        AppendToStringMethod(sb, typeName);
        sb.AppendLine();

        // Equals & GetHashCode
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public bool Equals(").Append(structName).AppendLine(" other) => Value == other.Value;");
        sb.AppendLine();
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public override bool Equals(object? obj) => obj is ").Append(structName).AppendLine(" id && Equals(id);");
        sb.AppendLine();
        
        AppendHashCodeMethod(sb, typeName);
        sb.AppendLine();

        // Operators
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public static bool operator ==(").Append(structName).Append(" a, ").Append(structName).AppendLine(" b) => a.Value == b.Value;");
        sb.AppendLine();
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public static bool operator !=(").Append(structName).Append(" a, ").Append(structName).AppendLine(" b) => a.Value != b.Value;");
        sb.AppendLine();

        // Implicit Operators
        AppendImplicitOperators(sb, structName, typeName, nullCast);

        // Closing
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{structName}_IdBindings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool IsNullable(string typeName) => typeName.EndsWith("?");

    private static void AppendToStringMethod(StringBuilder sb, string typeName)
    {
        sb.Append("        public override string ToString() => ");

        if (IsNullable(typeName))
        {
            sb.AppendLine("Value?.ToString() ?? string.Empty;");
            return;
        }

        sb.AppendLine("Value.ToString();");
    }

    private static void AppendHashCodeMethod(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public override int GetHashCode() => ");
        
        if (IsNullable(typeName))
        {
            sb.AppendLine("Value?.GetHashCode() ?? 0;");
            return;
        }

        sb.AppendLine("Value.GetHashCode();");
    }

    private static void AppendImplicitOperators(StringBuilder sb, string structName, string typeName, bool nullCast)
    {
        if (!IsNullable(typeName) || nullCast)
        {
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.Append("        public static implicit operator ").Append(typeName).Append("(").Append(structName).AppendLine(" id) => id.Value;");
            sb.AppendLine();
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.Append("        public static implicit operator ").Append(structName).Append("(").Append(typeName).AppendLine(" value) => new(value);");
            return;
        }

        var valueTypeName = typeName.TrimEnd('?');
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public static implicit operator ").Append(valueTypeName).Append("(").Append(structName).AppendLine(" id) => id.Value ?? default;");
        sb.AppendLine();
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        public static implicit operator ").Append(structName).Append("(").Append(valueTypeName).AppendLine(" value) => new(value);");
    }
}
